---
output:
  pdf_document:
    toc: yes
    toc_depth: 5
    fig_caption: true
    keep_tex: true
    number_sections: true
    latex_engine: xelatex
    includes:
      before_body: portada.tex
fontsize: 11pt
mainfont: Arial
lang: es
header-includes:
  - \usepackage{float}
  - \usepackage{graphicx}
  - \usepackage{geometry}
  - \usepackage{float}
  - \floatplacement{figure}{H}
editor_options: 
  markdown: 
    wrap: 72
bibliography: References.bib
---

# Introducción

La metformina es el tratamiento de primera línea para la diabetes tipo 2 debido a su eficacia para disminuir la gluconeogénesis hepática y mejorar la sensibilidad a la insulina. Además de su acción antihiperglucémica, este fármaco presenta múltiples efectos pleiotrópicos en diversos procesos biológicos, entre ellos la inflamación, el estrés oxidativo, la senescencia celular, la autofagia y la apoptosis, todos estrechamente vinculados con el envejecimiento. Estudios epidemiológicos han sugerido un posible efecto geroprotector de la metformina, asociado con la reducción en la incidencia de enfermedades relacionadas con la edad, como las enfermedades cardiovasculares, distintos tipos de cáncer y padecimientos neurodegenerativos, así como con una disminución de la mortalidad independiente de sus efectos sobre el metabolismo de la glucosa.

El músculo esquelético desempeña un papel central en a homostasis metabólica del organismos y es particularmente suceptible a los cambios asociados al envejeciemiento. La peridad progresiva de masa y función celular, junto con alteraciones en la sensibilidad a la insulina y en la capacidad oxidativa, contribuyen al deterioro de la calidad de vida en adultos mayores. Comprender cómo la metformina modula la biología molecular del músculo esquelético puede aportar unformación clave sobre como los mecanismos mediante los cuaes este fármaco influye en la salud durante el envejecimiento. 

En este proyecto se analizarán datos de secuenciación de ARN (RNA-seq) previamente publicados por Kulkarni et al. (2018), generados a partir de muestras de músculo esquelético de adultos de aproximadamente 70 años de edad (n=14). El estudio original se diseñó como un ensayo aleatorizado, doble ciego, controlado con placebo y con esquema cruzado, en el cual los participantes recibieron seis semanas de tratamiento con metformina y seis semanas con placebo.

Con base en este diseño, el objetivo del presente proyecto es reanalizar los datos de RNA-seq mediante un flujo de trabajo reproducible de bioinformática y estadística. Específicamente, se realizará la identificación de genes diferencialmente expresados entre las condiciones de metformina y placebo, con el propósito de explorar los programas transcriptómicos modulados por el tratamiento en músculo esquelético envejecido.